webtalk_init -webtalk_dir /media/2TB/workspace/rsarwar/work/TE1001_160/refdesign/test_board/workspace/sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-09-13 09:45:52" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174118286_178937913_210573335_948" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "tn66nlr30dkv3ofq70rlkrppv0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "KDE neon User Edition 5.16" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen Threadripper 2950X 16-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2052.003 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "67.426 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1568364134000" -context "sdk\\\\bsp/1568364134000"
webtalk_add_data -client sdk -key hwid -value "1564523195000" -context "sdk\\\\bsp/1568364134000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1568364134000"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1568364134000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1568364134000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1568364352190"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1568364352190"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1568364352190"
webtalk_add_data -client sdk -key DebugCount -value "2" -context "sdk\\\\bsp/1568364352190"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1568364352190"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1568364352190"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1568364352190"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1568364352190"
webtalk_transmit -clientid 1291565735 -regid "174118286_178937913_210573335_948" -xml /media/2TB/workspace/rsarwar/work/TE1001_160/refdesign/test_board/workspace/sdk/webtalk/usage_statistics_ext_sdk.xml -html /media/2TB/workspace/rsarwar/work/TE1001_160/refdesign/test_board/workspace/sdk/webtalk/usage_statistics_ext_sdk.html -wdm /media/2TB/workspace/rsarwar/work/TE1001_160/refdesign/test_board/workspace/sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
